name: parsec_windows
description: Windows implementation of the parsec plugin.
version: 0.2.0
repository: https://github.com/oxeanbits/parsec_flutter/tree/main/parsec_windows

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  parsec_platform_interface:
    path: ../parsec_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    implements: parsec
    platforms:
      windows:
        pluginClass: ParsecWindowsPluginCApi
        dartPluginClass: ParsecWindows
