name: parsec_platform_interface
description: A common platform interface for the parsec plugin.
version: 0.1.1
repository: https://github.com/oxeanbits/parsec_flutter/tree/main/parsec_platform_interface

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
