name: parsec
description: Multi-platform `parsec` plugin for Flutter to calculate math equations using C++ library. Supports android.
version: 0.3.1
repository: https://github.com/oxeanbits/parsec_flutter/tree/main/parsec

publish_to: "none"
environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  parsec_platform_interface:
    path: ../parsec_platform_interface
  parsec_android: #^0.3.2
    path: ../parsec_android
  parsec_linux:
    path: ../parsec_linux
  parsec_windows:
    path: ../parsec_windows
  parsec_web:
    path: ../parsec_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        default_package: parsec_android
      linux:
        default_package: parsec_linux
      windows:
        default_package: parsec_windows
      web:
        default_package: parsec_web
