name: parsec
description: Multi-platform `parsec` plugin for Flutter to calculate math equations using C++ library. Supports Android, Linux, Windows, and Web (WebAssembly).
version: 0.5.0
repository: https://github.com/oxeanbits/parsec_flutter/tree/main/parsec

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  parsec_platform_interface: ^0.2.1
  parsec_android: ^0.4.0
  parsec_linux: ^0.4.0
  parsec_windows: ^0.2.0
  parsec_web:
    path: ../parsec_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  web: ^0.5.1

flutter:
  plugin:
    platforms:
      android:
        default_package: parsec_android
      linux:
        default_package: parsec_linux
      windows:
        default_package: parsec_windows
      web:
        default_package: parsec_web
