name: Flutter CI (Basic)

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze packages
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.0
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Suppress path dependency warnings (pre)
        run: |
          set -euo pipefail
          for dir in parsec parsec_android parsec_linux parsec_windows parsec_web parsec_platform_interface; do
            f="$dir/pubspec.yaml"
            if [ -f "$f" ]; then
              cp "$f" "$f.backup"
              if ! grep -qE '^\s*publish_to:' "$f"; then
                printf "\npublish_to: none\n" >> "$f"
              fi
            fi
          done

      - name: Analyze parsec_platform_interface
        run: |
          cd parsec_platform_interface
          flutter pub get
          flutter analyze --no-fatal-infos

      - name: Analyze parsec
        run: |
          cd parsec
          # Add dependency overrides for CI testing
          echo "" >> pubspec.yaml
          echo "dependency_overrides:" >> pubspec.yaml
          echo "  parsec_platform_interface:" >> pubspec.yaml
          echo "    path: ../parsec_platform_interface" >> pubspec.yaml
          echo "  parsec_android:" >> pubspec.yaml
          echo "    path: ../parsec_android" >> pubspec.yaml
          echo "  parsec_linux:" >> pubspec.yaml
          echo "    path: ../parsec_linux" >> pubspec.yaml
          echo "  parsec_windows:" >> pubspec.yaml
          echo "    path: ../parsec_windows" >> pubspec.yaml
          echo "  parsec_web:" >> pubspec.yaml
          echo "    path: ../parsec_web" >> pubspec.yaml

          flutter pub get
          flutter analyze --no-fatal-infos

      - name: Analyze parsec_android
        run: |
          cd parsec_android
          flutter pub get
          flutter analyze --no-fatal-infos

      - name: Analyze parsec_linux
        run: |
          cd parsec_linux
          flutter pub get
          flutter analyze --no-fatal-infos

      - name: Analyze parsec_windows
        run: |
          cd parsec_windows
          flutter pub get
          flutter analyze --no-fatal-infos

      - name: Analyze parsec_web
        run: |
          cd parsec_web
          flutter pub get
          flutter analyze --no-fatal-infos

      - name: Restore pubspec.yaml backups (post)
        if: always()
        run: |
          set -euo pipefail
          for dir in parsec parsec_android parsec_linux parsec_windows parsec_web parsec_platform_interface; do
            f="$dir/pubspec.yaml"
            if [ -f "$f.backup" ]; then
              mv "$f.backup" "$f"
            fi
          done
